apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: btosq4occ-python 
  janus-idp.io/tekton: btosq4occ-python
  backstage.io/kubernetes-id: btosq4occ-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: btosq4occ-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml