apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: btosq4occ-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: btosq4occ-python 
  name: btosq4occ-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: btosq4occ-python 
